"""empty message

Revision ID: 0d7afab582a5
Revises: 972f055855a9
Create Date: 2024-01-04 12:39:13.711410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d7afab582a5'
down_revision = '972f055855a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment_requests')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_name', sa.Integer(), nullable=False))
        batch_op.drop_constraint('questions_quiz_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quizzes', ['quiz_name'], ['quiz_name'])
        batch_op.drop_column('quiz_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('questions_quiz_id_fkey', 'quizzes', ['quiz_id'], ['id'])
        batch_op.drop_column('quiz_name')

    op.create_table('enrollment_requests',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('course_id', name='enrollment_requests_pkey')
    )
    # ### end Alembic commands ###
