"""empty message

Revision ID: 2b0fb74ee139
Revises: 0d7afab582a5
Create Date: 2024-01-04 13:19:48.804541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0fb74ee139'
down_revision = '0d7afab582a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enrollment_requests')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['quiz_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('enrollment_requests',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('course_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('course_id', name='enrollment_requests_pkey')
    )
    # ### end Alembic commands ###
