"""empty message

Revision ID: 307342330ba3
Revises: 
Create Date: 2023-12-21 05:04:24.943758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307342330ba3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_option',
               existing_type=sa.VARCHAR(length=1),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.alter_column('correct_option',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=1),
               existing_nullable=True)

    # ### end Alembic commands ###
