"""empty message

Revision ID: 4dd2f59fa1a3
Revises: 889e1f400afa
Create Date: 2024-01-04 16:07:18.035241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd2f59fa1a3'
down_revision = '889e1f400afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit', sa.Integer(), nullable=True))
        batch_op.drop_column('time_limit_minutes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('time_limit')

    # ### end Alembic commands ###
