"""empty message

Revision ID: 889e1f400afa
Revises: 2b0fb74ee139
Create Date: 2024-01-04 15:58:46.691742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '889e1f400afa'
down_revision = '2b0fb74ee139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_limit_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('availability_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_column('availability_date')
        batch_op.drop_column('time_limit_minutes')

    # ### end Alembic commands ###
