"""empty message

Revision ID: 972f055855a9
Revises: aca4d5680235
Create Date: 2024-01-02 04:22:34.756268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972f055855a9'
down_revision = 'aca4d5680235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_students')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_students',
    sa.Column('quiz_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], name='quiz_students_quiz_id_fkey'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='quiz_students_student_id_fkey'),
    sa.PrimaryKeyConstraint('quiz_id', 'student_id', name='quiz_students_pkey')
    )
    # ### end Alembic commands ###
